spring:
  application:
    name: gameservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://patchnotes-db:3306/patchnotesDB?useSSL=false&serverTimezone=UTC&reWriteBatchedInserts=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create and drop table, good for testing, production set to none or comment it
    properties:
      jdbc:
        batch-size: 500
        order-inserts: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: password

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

logging:
  level:
    org:
      springframework:
        security: DEBUG
        netflix: DEBUG
        web:
          reactive: DEBUG
        cloud:
          gateway: TRACE
          netflix:
            eureka: DEBUG
          client:
            loadbalancer: DEBUG
    com:
      netflix:
        discovery: DEBUG
