spring:
  application:
    name: gameservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/patchnotesDB?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create and drop table, good for testing, production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: password

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

# logging:
#   level:
#     org:
#       springframework:
#         security: DEBUG
#         web:
#           reactive: DEBUG
#         cloud:
#           netflix:
#             eureka: DEBUG