spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/api/auth/**,/api/users/**
            - Method=GET,POST,PUT,DELETE
        - id: game-service
          uri: lb://gameservice
          predicates:
            - Path=/api/games/**,/actuator/health
            - Method=GET,POST,PUT,DELETE
#   data:
#     redis:
#       host: redis
#       port: 6379

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ #http://admin:password@localhost:8761/eureka #rep;ace with eureka-server in docker version of this file

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: INFO
        netflix: INFO
        web:
          reactive: INFO
        cloud:
          gateway: INFO
          netflix:
            eureka: INFO
          client:
            loadbalancer: INFO

jwt: # change secret
  secret: 8d7caec7c5cdc2e69d174e54fb8253ee0e929c5a295651629fcdab24667da806
  expiration: 3600000  # 1 hour in milliseconds