spring:
  application:
    name: gateway
  # profiles:
  #   active: debug
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: userservice-route
          uri: lb://userservice
          predicates:
            - Path=/api/auth/**,/api/users/**
            - Method=GET,POST,PUT,DELETE
        - id: gameservice-route
          uri: lb://gameservice
          predicates:
            - Path=/api/games/** #,/actuator/health
            - Method=GET,POST,PUT,DELETE

#   data:
#     redis:
#       host: redis
#       port: 6379

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #http://admin:password@localhost:8761/eureka

server:
  port: 8080

jwt: # change secret
  secret: 8d7caec7c5cdc2e69d174e54fb8253ee0e929c5a295651629fcdab24667da806
  expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    org:
      springframework:
        security: DEBUG
        netflix: DEBUG
        web:
          reactive: DEBUG
        cloud:
          gateway: TRACE
          netflix:
            eureka: DEBUG
          client:
            loadbalancer: DEBUG
    com:
      netflix:
        discovery: DEBUG