FROM node:18

WORKDIR /app

# Copy package.json and yarn.lock
COPY frontend/web/package.json frontend/web/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the web code
COPY frontend/web .

# Copy shared code
COPY frontend/shared ./src/shared

# Expose port 3000
EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]