spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://patchnotes-db:3306/patchnotesDB?useSSL=false&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create and drop table, good for testing, production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: password

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

logging:
  level:
    org:
      springframework:
        security: INFO
        web:
          reactive: INFO
        cloud:
          netflix:
            eureka: INFO
jwt:
  secret: 8d7caec7c5cdc2e69d174e54fb8253ee0e929c5a295651629fcdab24667da806
  expiration: 3600000  # 1 hour in milliseconds

game:
  service:
    url: http://gameservice:8083