FROM node:18

WORKDIR /app

# Copy package.json and yarn.lock
COPY frontend/mobile/package.json frontend/mobile/yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the mobile code
COPY frontend/mobile .

# Copy shared code
COPY frontend/shared ./src/shared

# Expose the Metro bundler port
EXPOSE 8081

# Start the Metro bundler
CMD ["yarn", "start"]