spring:
  application:
    name: eureka-service
  security:
    user:
      name: admin
      password: password

server:
  port: 8761

eureka:
  instance:
      prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://admin:password@localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    #enable-self-preservation: false

#change to info
# logging:
#   level:
#     com:
#       netflix:
#         eureka: DEBUG
#         discovery: DEBUG